export const discArray = [

    { Name: 'Destroyer', Category: 'Distance driver', Speed: 12, Glide: 5, Turn: -1, Fade: 3, Description: "The Destroyer is overstable, but has a degree of turn to help provide incredible glide and distance. Intermediate players will get more distance on forehand throws with the Destroyer than just about any other disc. The Innova Destroyer is a very thin (1.4cm) disc, and has the perfect sized rim (2.2cm) for high speeds, without being uncomfortably thick. As such a popular driver, the Destroyer comes available in all the major plastics.", Image: "destroyer.jpeg" },
	{ Name: 'River', Category: 'Fairway driver', Speed: 7, Glide: 7, Turn: -1, Fade: 1, Description: "The Latitude 64 River is one the highest rated fairway drivers. It has incredible glide and is a great driver for beginners. Latitude gives this disc a glide rating of 7, higher than any other disc golf disc. Intermediate and advanced players will be pleased with the River’s accuracy and consistency. Throw this disc at a slight anhyzer angle and watch it sail forever.", Image: "River.jpeg"},
	{ Name: 'Zone', Category: 'Putter', Speed: 4, Glide: 3, Turn: 0, Fade: 3, Description: "Want to get in the Zone? The Discraft Zone is a slim putter with a thick rim (1.2cm) that gives you something to hold on to. This is a very overstable putter that is good for headwinds, strategic fades, forehand throws, flick putts, and slamming into chains at just the right angle. Many Discraft enthusiasts will have a Zone in their bag as a putter that gets them out of a situation where a Flick, or sidearm putt is their only option. Being so overstable, this disc can handle the torque that a Flick will put on it!", Image: "zone.jpeg" },
	{ Name: 'Tern', Category: 'Distance driver', Speed: 12, Glide: 6, Turn: -3, Fade: 2, Description: "The Tern is an understable high speed driver. Being understable, this is a comfortable disc that provides max distance for intermediate players. While the Tern’s rim is very wide (2.3 cm) it isn’t at max width like the Dominator, Vulcan, or Katana. The Innova Tern was approved by the PDGA on December 3, 2012. Innova states that the flight rating of this disc in Star and Champion plastic slightly differ. The flight rating for Champion Plastic is 12/6/-2/2. The Champion plastic that the Tern is manufactured in is super clear and looks really sharp", Image: "tern.jpeg" },
	{ Name: 'Wraith', Category: 'Distance driver', Speed: 11, Glide: 5, Turn: -1, Fade: 3, Description: "The Innova Wraith is a long stable distance driver with decent speed, exceptional glide, and precision accuracy. Players of many different skill levels can get great distance with the Wraith. The neutral stability of the Wraith allow it to be a valuable disc in all wind conditions. This driver works well for both forehand and backhand throws.", Image: "Wraith.jpg" },
	{ Name: 'RocX3', Category: 'Midrange', Speed: 5, Glide: 4, Turn: 0, Fade: 3.5, Description: "The Innova RocX3 is the most overstable version of the popular Roc midrange. Compared with other Roc versions, the X3 is a low profile and hefty rim that provide it with extra stability. Innova claims that this is the ideal midrange for windy conditions and forehand throws. Power throwers love the consistency and control.", Image: "rocx.jpeg" },
	{ Name: 'Mako3', Category: 'Midrange', Speed: 5, Glide: 5, Turn: 0, Fade: 0, Description: "The Mako3 is the newest version of the remarkably straight flying Innova Mako. This midrange disc is the perfect solution for anyone who wants a straight flyer with very limited fade. The Mako3 is available in the new Jolly Launcher Champion plastic, and is slightly faster than the original Mako", Image: "mako3.jpeg" },
	{ Name: 'Comet', Category: 'Midrange', Speed: 4, Glide: 5, Turn: -2, Fade: 1, Description: "The Discraft Comet is a very popular straight-flying, slightly understable midrange disc. This is a versatile disc that can handle all kinds of shots and conditions. Discraft gives the Comet a stability rating of 0. The Comet is available in the premium and highly durable ESP and Z plastics.", Image: "comet.jpeg" },
	{ Name: 'FD', Category: 'Fairway driver', Speed: 7, Glide: 6, Turn: -1, Fade: 1, Description: "The FD Jackal is truly one of the great straight flying fairway drivers. This disc is perfect for straight line shots through low ceiling tree lines. As an accurate smooth flying disc, the FD is a winner for beginners and pros. While the Jackal isn’t the fastest flying fairway driver, it does offer excellent glide. Discmania gives the Jackal a glide rating of 6. This fine disc is available in a variety of plastics.", Image: "fd.jpeg" },
	{ Name: 'Avenger', Category: 'Distance driver', Speed: 10, Glide: 5, Turn: 0, Fade: 3, Description: "The Discraft Avenger is an overstable distance driver good for intermediate and advanced players. It is one of the primary drivers that helped Nate Doss win the 2005 Pro World Championships. With a level throw the Avenger will fly in a moderate hooking motion. Throw it at an anhyzer angle and the Avenger will provide a nice S-Curve. Discraft gives the Avenger a stability rating of 1.6 for Elite X plastic, and 1.8 for their other plastic blends.", Image: "avenger.jpeg" },
	{ Name: 'Leopard', Category: 'Distance driver', Speed: 6, Glide: 5, Turn: -2, Fade: 1, Description: "The Leopard is the classic straight flying Innova fairway driver. This disc is very popular in starter sets thanks to the reliable flight path and limited fade. It’s not the fastest flying disc (speed 6) but new players will likely see more distance with the Leopard than just about any other disc. While the Leopard is great for beginners, it can be found bags of more advanced players as well. With moderate throws this disc is perfect for weaving between narrow lines of trees. It also makes a good turnover driver that slices to the right, and a good roller disc", Image: "leopard.jpeg" },
	{ Name: 'Teebird', Category: 'Fairway driver', Speed: 7, Glide: 5, Turn: 0, Fade: 2, Description: "The TeeBird is a classic disc by Innova. It is a popular fairway driver for many disc golfers. Made for straight lines with an easy steady fade throughout its flight, the TeeBird is a dependable all around control driver. This disc set the standard for driving consistency and is the disc that all new models are compared with.", Image: "teebird.jpeg" },
	{ Name: 'Luna', Category: 'Putter', Speed: 3, Glide: 3, Turn: 0, Fade: 3, Description: "The Luna is the first putter in the Paul McBeth line for Discraft. It is his primary putter and it more overstable than a lot of other putters. It works great as a low-glide, beadless putter for players who putt with a lot of confidence. It will be a popular putter due to the reputation of Paul McBeth as a winner and will serve other experienced players well.", Image: "luna.jpeg" },
	{ Name: 'Mercy', Category: 'Putter', Speed: 2, Glide: 4, Turn: 0, Fade: 1, Description: "The Mercy is a slow speed putter with a deep rim. It has a great feel and is available in a variety of Latitude 64's high end plastics, as well as it's baseline plastic.", Image: "mercy.jpeg" },
	{ Name: 'Aviar', Category: 'Putter', Speed: 2, Glide: 3, Turn: 0, Fade: 1, Description: "The Aviar is the most popular putter in the world. It is a good disc for short drives and approach shots, as well as rattling the chains.", Image: "aviar.jpeg" }
    

];